//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RssStarterKit.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RssStarterKit.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar.
        /// </summary>
        public static string FeedView_AppBar_Button_Refresh {
            get {
                return ResourceManager.GetString("FeedView_AppBar_Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última atualização: .
        /// </summary>
        public static string FeedView_LastUpdated {
            get {
                return ResourceManager.GetString("FeedView_LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações.
        /// </summary>
        public static string FeedView_PivotHeader_FeedInfo {
            get {
                return ResourceManager.GetString("FeedView_PivotHeader_FeedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notícias.
        /// </summary>
        public static string FeedView_PivotHeader_NewsItems {
            get {
                return ResourceManager.GetString("FeedView_PivotHeader_NewsItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        public static string ItemView_AppBar_Button_Open {
            get {
                return ResourceManager.GetString("ItemView_AppBar_Button_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartilhar.
        /// </summary>
        public static string ItemView_AppBar_Button_Share {
            get {
                return ResourceManager.GetString("ItemView_AppBar_Button_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O item que você seleccionou item não tem conteúdo. Por favor, visite o site usando o botão abaixo para ler este post..
        /// </summary>
        public static string ItemView_FeedItemHasNoContent {
            get {
                return ResourceManager.GetString("ItemView_FeedItemHasNoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About RssStarterKit text.
        /// </summary>
        public static string MainView_About_Body {
            get {
                return ResourceManager.GetString("MainView_About_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string MainView_About_Title {
            get {
                return ResourceManager.GetString("MainView_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        public static string MainView_AppBar_Menu_About {
            get {
                return ResourceManager.GetString("MainView_AppBar_Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rede indisponível.
        /// </summary>
        public static string MainView_NetworkErrorMessage {
            get {
                return ResourceManager.GetString("MainView_NetworkErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novas Notícias.
        /// </summary>
        public static string MainView_Title {
            get {
                return ResourceManager.GetString("MainView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rede não está disponível atualmente - alguns recursos do aplicativo será desativado até que rede é restaurada. Pressione o botão &quot;back&quot; para continuar a utilizar os dados em cache, ou sair do aplicativo e tente novamente mais tarde..
        /// </summary>
        public static string NetworkNotAvailableMessage {
            get {
                return ResourceManager.GetString("NetworkNotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique para atualizar.
        /// </summary>
        public static string NoDataCollectedConverterText {
            get {
                return ResourceManager.GetString("NoDataCollectedConverterText", resourceCulture);
            }
        }
    }
}
